### PR TITLE
Add bounds exceptions to FilterBasic

### PR DESCRIPTION
**Pull request by ntindall**
Not sure if Q bounding is desired.

### CODE REVIEW

**Comment by spencersalazar** [comment]
Awesome! Everyone's ears will thank you. 

Bounding Q is great (in practice Ive noticed it can cause problems for small values > 0 but 0 is a good start). Probably is good to bound upper frequency to Nyquist also. 

@gewang @lathertonj how do you guys feel about this i.e. raising an "exception" on invalid/erroneous arguments to the parameters of LPF/HPF etc.? This will hopefully fix a lot of problems with these filters blowing up.

**Comment by lathertonj** [comment]
It's probably a good idea! But (for example) there was one SLOrk instrument this year that was based around having parameters be out of their normal / valid ranges most of the time.  I do wonder if there is some artistic merit to abusing UGens in this way that we should try to preserve.

As far as raising an exception that halts execution, I hesitate to do so in case the problem is some fleeting thing that's fixed by the programmer on a future sample (e.g. buggy initialization or improper parameter control), though maybe it's a good idea to encourage programmers to fix such errors.

One possibility is adding an exception-suppressing flag to each UGen (or a global flag) that, if set, allows the old/current behavior, but if left unset (default), throws exceptions on invalid parameters.

One possibility is to just throw exceptions on any invalid parameters and completely drop the old behavior (as in this diff).

Two more options: instead of throwing an exception, clamp all incoming parameters to valid ranges (and either have a flag for toggling this behavior or just do it in every case).

I am curious to hear thoughts on this!

As far as the name of the exception, I might suggest something more general like `InvalidFrequencyException` or even `InvalidParameterException` -- the description can add the necessary context of what parameter was invalid and how it was invalid.

(It might be a good idea also to add line numbers to error messages from `throw_exception`, but that's a more involved project that would entail making sure every `Chuck_Instr` has a line number instead of just the select few that can throw errors from within their `::execute` functions (bypassing `throw_exception`).)

**Comment by markcerqueira** [comment]
@lathertonj, I like the "adding an exception-suppressing flag to each UGen (or a global flag) that, if set, allows the old/current behavior, but if left unset (default), throws exceptions on invalid parameters."

**Comment by spencersalazar** [comment]
Definitely- its important to preserve the capability to push parameters outside their nominal limits and I don't think its necessary or useful to aggressively sanitize UGen parameter values in the general case. 

LPF/HPF and friends however are some of the few unit generators in ChucK that are capable of abruptly causing physical damage (to speakers and/or ears) when pushed outside their normal parameter range in normal usage. This a problem that beginners and even experienced ChucK users (*cough* like myself *cough*) come across frequently enough. So theres a strong argument for by-default input validation specifically for the FilterBasic filters. 

Another option, for people who know what theyre doing and want to break the "rules," is to add separate "expert mode" controls for freq/Q on these filters, which would not validate input. This is similar to [] and at() with C++ vector's where one of them validates the index and one does not. Or yeah a per-instance flag seems like a fair compromise between ease-of-use and modularity. Im less excited about global flags as this will cause problems integrating multiple bodies of code that expect the flag to be set in conflicting ways. 

Re: line numbers in these exceptions- that would definitely be helpful. I wonder if it would be enough to track the line number in the Func_Call instructions since thats how any parameter setter would be accessed.

**Comment by lathertonj** [comment]
In that case, I think the best thing to do is to add in exception protection thoroughly for FilterBasic filters at this point, and consider adding in "expert mode" with low priority some time later in the future.

I'll put up a commit with line numbers in these exceptions sometime soon.  `throw_exception` seems to be currently used only by regexes, osc, and string static/member functions, so enabling line numbers for Func_Call / Func_Call_Static / Func_Call_Member should cover everything. Good idea!

**Comment by heuermh** [comment]
Rather than flags, I'd prefer separate `setUnsafe` or similarly-named expert-use-only methods that bypass bounds checking.  As for exceptions, is there now try catch finally syntax in ChucK?

**Comment by gewang** [comment]
Thanks @ntindall and all for this.  This has been applied to LPF, HPF, BPF, BRF (but not to others like ResonZ for now, leaving them open for experimentation as they don't seem to blow up in the same way, but I could be wrong).  We should revisit if problems persist.  — ChucKian ears across the land.

**Comment by ntindall** [comment]
🙌 thanks @gewang

**Pull request merged**
