### PR TITLE
stop ignoring midi clock in messages

### PR DESCRIPTION
**Pull request by brulo**

### CODE REVIEW

**Comment by spencersalazar** [comment]
Nice! The CI failure is most likely an unrelated issue. I think if it were to try again it would go through.

**Comment by rawray7** [comment]
as far as i can tell, chuck 1.3.5.1 is still not receiving midi clock messages. only tried ableton live 9 tho. has this been tested?

**Comment by spencersalazar** [comment]
This merge has come after the latest release version (1.3.5.1). Until the next release, you'd need to build from source to try it.

**Comment by rawray7** [comment]
cool thanks. works after building the current master (0dc21a8271c6c9e575a9fd1d36a085facb82ddcd), tested with Ableton 9.

**Comment by spencersalazar** [comment]
Sweet, thanks for testing and letting us know!

**Pull request merged**
