### PR TITLE
fixed #116 #144 #119 #130 #122

### LINKED ISSUE #116: ADSR.decayTime() returns "nan"
*Environment:*
Chuck 1.4 (numchucks)
Mac OS X High Sierra

*Description:*
I noticed that the function decayTime() is not returning a valid duration value at the moment. In the following minimum working example:

```chuck
SinOsc sin => ADSR env => dac;
env.set(second, second, 1., second);

<<< "Attack Time: ", env.attackTime() >>>;
<<< "Decay Time: ", env.decayTime() >>>;
<<< "Sustain Level: ", env.sustainLevel() >>>;
<<< "Release Time: ", env.releaseTime() >>>;
```

*Expected result:* 
env.decayTime() returns the current envelope decay time as a valid dur.

*Result:* 
env.decayTime() returns "nan". Seems to be the only envelope getter to be broken at the moment.

### PR DESCRIPTION
**Pull request by mariobuoninfante**

### CODE REVIEW

**Comment by gewang** [comment]
Thank @mariobuoninfante for your work on this. This PR was failing the integration testing on ADSR-2.ck so I took a comprehensive look at ADSR and ended up patching it up throughout. Now it should no longer fail when sustain is either 1 or 0 and decayTime/releaseTime returns NaN and ADSR audio outputs zero thereafter even with new parameters. Overall, made things hopefully more robust to various edge cases. The changes were pushed as of 20d717e and will be incorporated in 1.4.0.2. Please feel free to stress test this more. Thank you!!

**Comment by gewang** [comment]
Thank you so much @mariobuoninfante. Due to the CI issue, and instead of asking you to resubmit the PR, I manually applied changes and added further code for ADSR, these can be found in 20d717eafea731bdee22975bc9c724110effa58d 86c58f0534d1d24fd31c31de6d2dca6440702511 bf52fc151dfd5b7347f360b005574362e0851b45 -- and all will be part o the next release 1.4.0.2.  Thank you!

**Comment by mariobuoninfante** [comment]
thanks @gewang for looking into this.
apologies if I made a bit of a mess with the PR, I'll be a bit more careful next time for sure! :)

**Comment by gewang** [comment]
Thank *you* @mariobuoninfante for attending to these issues. If you'd like, feel free to submit separate PRs instead of monolithic ones that address multiple issues. The modularity makes it easier to verify and integrate them independently. Thank you once again!

**Pull request closed without merging**
