### PR TITLE
RtAudio Update

### PR DESCRIPTION
**Pull request by nshaheed**
(This is built off of #198, but github is being a butt so I'm making a new PR).

In addition to updating the visual studio project to handle the new imports and making the `--driver` flag more forgiving I've migrated the newest rtaudio library out of a submodule and into the main repo, which we can discuss here @gewang).

Thanks again @dbadb!

### CODE REVIEW

**Comment by dbadb** [comment]
sounds like a good workaround... Let me know when I should retract/cancel mine?

**Comment by dbadb** [comment]
On the topic of windows drivers,  I read somewhere online that wasapi is now the preferred non-asio driver for audio production.  One internet denizen claimed that latencies for wasapi are competitive with asio but I haven't verified this.  In my custom chuck builds I regularly enable all three so I can easily switch and compare.  Also, when selecting a default input or output device in the Sound control panel, I don't think the distinction between ds and wasapi is apparent to the user.  If indeed wasapi is superior to ds, it might be wise to make that the default.

**Comment by znmeb** [comment]
> On the topic of windows drivers, I read somewhere online that wasapi is now the preferred non-asio driver for audio production. One internet denizen claimed that latencies for wasapi are competitive with asio but I haven't verified this. In my custom chuck builds I regularly enable all three so I can easily switch and compare. Also, when selecting a default input or output device in the Sound control panel, I don't think the distinction between ds and wasapi is apparent to the user. If indeed wasapi is superior to ds, it might be wise to make that the default.

<rant>Windows audio is a confusing morass. Just last night, I installed an open source package that requires JACK to communicate with other audio processes, like digital audio workstations. So I installed JACK for Windows.

JACK requires an audio interface setup, so I went into the setup menu. There are three MME options,  three Windows DirectSound options, two Windows WASAPI options, and *ten* Windows WDM-KS options! So the two audio devices I have, Realtek and NVIDIA, have multiple ways to talk to them.

IMHO this is a usability failure on Microsoft's part. Microsoft needs to pick ***ONE***; I shouldn't have to go search the internet for pros and cons of each one! I'm trying to make music here, not benchmark drivers. :-( </rant>

**Comment by dbadb** [comment]
@znmeb  - I'm with you 100%.  Windows audio is a bit of a mess (esp relative to MacOS) and if you then bring Jack to the party, well...   Part of the issue for end-users is that developers have no hope of selecting the "one best solution" that will work for all users.  That's a developer's justification for punting the problem to the user.  In the case of chuck, the new --driver:ASIO,WASAPI,DS arg is the analog of the choices presented to you by JACK.   The hope is, we can offer the best generic option by default, then only allow users to override that choice if they have a good reason to.

FWIW: here is a link to the "Core Audio APIs": https://learn.microsoft.com/en-us/windows/win32/coreaudio/about-the-windows-core-audio-apis - the doc is still talking about Vista and Windows 7 as "new".

Note that JACK isn't on this list, it sits atop one or more of these presumably.

**Comment by nshaheed** [comment]
After some very quick initial testing it looks like that might be the case - especially with dedicated audio interfaces it looks like wasapi is much lower latency than DS. This was in no way exhaustive so if anyone has any more authoritative info, we'll probably be discussing this pr internally later in the week, so anything that points to the better option would be awesome

**Comment by dbadb** [comment]
@nshaheed : should you decide to make WASAPI the default driver on windows, the one line change could be applied to chuck_audio.cpp (line 144?).

```c++
   if(api == RtAudio::UNSPECIFIED)
    {
    #if defined(__PLATFORM_WIN32__)
        // traditional chuck default behavior:
        // DIRECT SOUND is most general albeit high-latency
        api = RtAudio::WINDOWS_DS;   // <---- the culprit
    #elif defined(__PLATFORM_LINUX__)
        api = RtAudio::LINUX_PULSE;
    #endif
    }
```

**Comment by nshaheed** [comment]
(leaving this here for future reference) It looks like WASAPI was introduced in [vista ](https://en.wikipedia.org/wiki/Technical_features_new_to_Windows_Vista#Audio_stack_architecture) so making it the default would cause headaches for anyone still running chuck on xp for some reason, and would be a breaking change for xp miniaudicle users (since there's no driver setting in miniaudicle atm). I estimate this would affect between 6 and -6 people

**Comment by znmeb** [comment]
> (leaving this here for future reference) It looks like WASAPI was introduced in [vista ](https://en.wikipedia.org/wiki/Technical_features_new_to_Windows_Vista#Audio_stack_architecture) so making it the default would cause headaches for anyone still running chuck on xp for some reason, and would be a breaking change for xp miniaudicle users (since there's no driver setting in miniaudicle atm). I estimate this would affect between 6 and -6 people

This will be a problem only if the Microsoft collection of virtual machines for browser testing includes XP. :-)

**Comment by gewang** [comment]
Thanks @dbadb @nshaheed and all for this epic PR; we have have gone through it and also took the opportunity to fix the long-standing bluetooth audio input issue; also re-ordered boot-up sequence to avoid a separate sample-rates issue; changed a few surface things in RtAudio source for pre-C++11 compatibility; there are few outstanding issues, including default to WASAPI, which we will create separate issues for. Just in time for chuck-1.5 release!! Thank you!!!

**Pull request merged**
