### PR TITLE
fixed #122 - Gen10 aliasing issue - #119 reset Gen10 table when calling .coefs()

### LINKED ISSUE #122: Gen10 issue with odd partials
Hi,

It seems like Gen10 has an issue when dealing with odd harmonics (not fundamental).
It's easy to repro taking the example code and using the following coefficients instead:
g10.coefs( [0., 0., 0.5] ); - shows the issue
g10.coefs( [0., 0.5, 0.] ); - doesn't show the issue
Hooking ChucK up to a spectrum analyzer it's easy to see the difference.
In case there are odd harmonics there are a lot of partials/sidebands, instead of having only the components specified in .coefs().
Tested on Ubuntu Studio 16.04 - ChucK 1.4.0

### PR DESCRIPTION
**Pull request by mariobuoninfante**

### CODE REVIEW

**Comment by spencersalazar** [comment]
Hey @mariobuoninfante, @gewang and I are looking at this now and we think it should be good to merge. We're just wondering if the MIDI changes here are good to go and would be ok to go in to the mainline chuck?

**Comment by spencersalazar** [comment]
Also, thanks!

**Comment by mariobuoninfante** [comment]
Hi Spencer,

I've been using ChucK on Ubuntu Studio 16.0 LTS with these changes in place since then, no issues at all.

That said you probably want to double check. 
The reasoning behind that change is that at row 1420 in rtmidi.cpp, there's a mismatch between what **snd_midi_event_encode** returns and the size of the message ChucK has passed (nBytes). Cause I suppose in the case of 1 and 2 bytes msg , ChucK still passes 3 bytes, of which the unused bytes are padded.

On the Alsa MIDI side we have **snd_midi_event_encode** (https://github.com/alsa-project/alsa-lib/blob/3ec6dce5198f100fa8dd2abfc1258fa4138ceb1a/src/seq/seq_midi_event.c - row 360) then calls **send_midi_event_encode_byte** (https://github.com/alsa-project/alsa-lib/blob/3ec6dce5198f100fa8dd2abfc1258fa4138ceb1a/src/seq/seq_midi_event.c - row 398). This I suppose the _real_ size of the messages (ie 1 or 2 bytes), discarding the 0s.

**Comment by mariobuoninfante** [comment]
Ideally we could have ChucK passing the right amount of bytes, also cause I noticed that the same happens on MacOS, where when you send a 1 or 2 byte msg, then spurious bytes get sent as well.
As shown in this screenshot
Screen Shot 2020-04-01 at 08 37 02

**Comment by mariobuoninfante** [comment]
also since we're talking about it, I think we should also add: 
```
rtmin->ignoreTypes(false, false, false); // or whatever other default settings we want to have here
```
on line 414 in midiio_rtmidi.cpp

because the flags set at row 242 of rtmidi.h aren't considered anywhere from what I can see.
Please let me know if this need its own ticket, happy to do so :)

Cheers,
Mario

**Comment by mariobuoninfante** [comment]
Hi @spencersalazar, 
would it be worth at least create a new PR were I tackle the Gen10 issue?

**Comment by spencersalazar** [comment]
@mariobuoninfante Sounds good! If its possible to avoid the whitespace changes btw it will make reading the PR and reviewing the changes a lot easier.

**Comment by mariobuoninfante** [comment]
Hi @spencersalazar,

Sure thing. Yeah that was an issue I was having when using Atom, not sure what was going on there. 
But I'll make a clean PR.
Thanks

**Pull request closed without merging**
