### PR TITLE
Update to latest RtAudio (as submodule). Support for runtime selection of audio driver.

### PR DESCRIPTION
**Pull request by dbadb**
Here we migrate the "burned-in" RtAudio support to utilize the official github version.

Costs:
- use of submodules may be a headache across branches. Or for non-pro-level git users.

Benefits: 
- latest and greatest RtAudio
- ability to have multiple drivers in the same chuck build. Currently we have validated cohabitation of Windows ASIO and DirectSound as well as Pulse, Alsa and Jack drivers in the same linux build.

Known issues:
- RtAudio no longer throws exceptions and some of the error reporting codepaths
  haven't been fully tested.

Usage/testing:
- no changes to the default builds have been made. And should still produce the same result.  If one edits a makefile or vsproj to include more RtApi driver requests (eg -D__WINDOWS_ASIO__) you can include multiple drivers in your build.  A new commandline option --driver is required to select the non-default driver...  For example:   `chuck --probe --driver:ASIO` vs `chuck --probe`

### CODE REVIEW

**Comment by dbadb** [comment]
These failure are due to the fact that the automation build hasn't properly initialized the new submodule.

**Comment by nshaheed** [comment]
Hey Dana, thanks for doing this! ASIO support is huge for windows. I've been working on this branch to get it up-to-date with the current head and polishing things, could you [enable permissions ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)on this pull request so that I can push my changes upstream and we can keep everyone consolidated to this PR?

**Comment by dbadb** [comment]
Hey Nick, happy to do this but at the risk of appearning dumb, where the * is the magic button?   On the link you provided I see: 

```
On user-owned forks, if you want to allow anyone with push access to the upstream repository to make changes to your pull request, select Allow edits from maintainers
```

I'm sure it's right in front of my nose, but my nose seems to be getting in the way. :-)

**Comment by nshaheed** [comment]
image

It should be in the bottom right corner! It looks like it defaulted to being enable for me, so maybe I just don't have the correct permissions to push

**Comment by dbadb** [comment]
Sadly - at this link: https://github.com/ccrma/chuck/pull/198,   that checkbox isn't present on my view. Perhaps it has something to do with whether I have push access to this repo?

image

**Comment by nshaheed** [comment]
Ah well, I guess github will continue being github. I put my updated in #269, so I'm going to close this PR and we can continue the discussion there.

**Pull request closed without merging**
